### ISSUE TITLE
Config struggle 

### ISSUE THREAD

**Issue by proudot** [aaronjensen/emacs-popup-mode#1]
Thanks for sharing code, this looks very useful to me. However, I am struggling to configure it. Am I doing anything wrong here ? It doesn't give an error but just doesn't do anything.

    (use-package popup-mode
      :straight (:type git :host github :repo "aaronjensen/emacs-popup-mode")
      :config
      (set-popup-rules! '(
    		    ("^\\*Org QL View" :side right :width +popup-shrink-to-fit :quit 'current :select t :modeline nil)
    		    ("^\\*Org QL View: Aims*" :side right :width 0.4 :quit 'current :select t :modeline nil)
    		    ))
      )

**Comment by aaronjensen** [comment]
Hi @proudot, you'll need to enable `+popup-mode`. Here's my config:

```el
(use-package popup-mode
  :demand t
  :hook (after-init . +popup-mode)

  :straight (popup-mode :host github :repo "aaronjensen/emacs-popup-mode")
  :bind (("C-`" . +popup/toggle))
  :config
  (set-popup-rules! '(("^\\*Process List\\*$"
                       :side bottom :select t :slot -1 :vslot -1 :size +popup-shrink-to-fit)
                      ("^\\*Buffer List\\*$"
                       :side bottom :select t :slot -1 :vslot -1 :size +popup-shrink-to-fit)
                      ("^\\*ruby-compilation\\*$"
                       :side bottom :select nil :slot -1 :vslot -1 :height 0.4 :ttl nil)
                      ("^\\*Messages\\*$"
                       :side bottom :select t :slot -1 :vslot -1 :height 0.3 :ttl nil))))
```

I just added an example to the README. Let me know if that doesn't work out.

**Comment by proudot** [comment]
Thanks for the lightning fast reply, it works great now! Do you know we have o call `+popup-mode` and `set-popup-rules!` instead of just `popup-mode` and `set-popup-rules` ? This is very useful and so much saner!

**Comment by aaronjensen** [comment]
It was extracted from Doom, which uses the `+` prefix. I may remove it since I don't really intend to get anything else from upstream. So if things stop working for you that may be why 😄
